FROM node:8.9.4

WORKDIR /myapp

COPY ./frontend/package.json ./frontend/yarn.lock ./
RUN npm install -g yarn
RUN yarn global add @angular/cli@7.3.9
RUN yarn install

COPY ./frontend ./

EXPOSE 4200
CMD ["ng", "serve", "-H", "0.0.0.0", "--disable-host-check"]
