FROM ruby:2.4.1

ENV LANG C.UTF-8

ENV DEBIAN_FRONTEND noninteractive

RUN sed -i '/jessie-updates/d' /etc/apt/sources.list  # Ref: https://github.com/debuerreotype/docker-debian-artifacts/issues/66

RUN apt-get update -qq && apt-get install -y \
      build-essential mysql-client libv8-dev cmake \
      && apt-get clean \
      && rm -rf /var/lib/apt/lists/*

WORKDIR /myapp

COPY Gemfile /myapp/Gemfile
COPY Gemfile.lock /myapp/Gemfile.lock
RUN gem install bundler
RUN bundle install --path=/usr/local/bundle --jobs=4 --retry=3

EXPOSE 3000

COPY .docker/start.sh /start.sh
RUN chmod +x /start.sh
CMD ["/start.sh"]
